### ISSUE TITLE
Get tests passing

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/views_data_export#1]
I've made a few tweaks to get the tests passing and got rid of straggling drupal functions and variable_gets. I'll share the PR.

(I was originally going to port this module then noticed it was already here!)

---
PR https://github.com/backdrop-contrib/views_data_export/pull/7

**Comment by herbdool** [comment]
@jlfranklin I made a PR with a few small changes. I hope it's okay all in one.

**Comment by herbdool** [comment]
@jlfranklin wonder if you'll have a chance to look at this. I could split up the PR if needed. Do you want help with this module?

**Comment by herbdool** [comment]
@laryn would you be able to test/review?

**Comment by laryn** [comment]
Can put it on my list -- maybe later tonight if I'm lucky!

**Comment by laryn** [comment]
I pulled changes and ran locally and tests all passed:

![Screen Shot 2019-12-17 at 7 58 10 PM](https://user-images.githubusercontent.com/871421/71049352-ad0cb400-2107-11ea-89e7-5f216f348daf.jpg)

**Comment by herbdool** [comment]
Thanks @laryn! So following protocol we can merge these bug fixes in a couple weeks.

@jlfranklin just want to alert you that there are a few bug fixes tested and reviewed. You've got a few choices: let me know you're going to handle them in some manner; let the Bug Fix Team handle them (by doing nothing this is the default); or give your approval for me to merge them and make a new release.

**Comment by herbdool** [comment]
As part of the Bug Fix Team I've merged this PR - tests should now pass. Thanks @laryn!
