### ISSUE TITLE
Drupal in warning and in code

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/views_data_export#3]
I moved a development site to a new host by request, and saw this error:

![Screen Shot 2019-05-29 at 1 32 00 PM](https://user-images.githubusercontent.com/871421/58585942-93fded80-821f-11e9-9c80-4939eccf268b.jpg)

From [this line](https://github.com/backdrop-contrib/views_data_export/blob/da093616525aee2bef399302ba7a5a1ee9760c51/views_data_export.install#L199). A few issues:

 - obviously not ideal to point to and mention Drupal instead of  Backdrop. (The Drupal link goes to a Drupal 8 page besides)
 - The [related Backdrop page](https://backdropcms.org/requirements) does not mention `max_allowed_packet`.

---
PR https://github.com/backdrop-contrib/views_data_export/pull/6

**Comment by herbdool** [comment]
@laryn I've got a PR. I figure we can update the Backdrop page later. The Drupal page doesn't `max_allowed_packet` either.

If you test/review this PR, as part of Bug Squad I can merge it. (See https://github.com/backdrop-ops/contrib)

**Comment by laryn** [comment]
@herbdool LGTM!

**Comment by herbdool** [comment]
As part of the Bug Fix Squad I've merged this bug fix.
