### ISSUE TITLE
Convert variable_ to config_

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/views_data_export#4]
When I copy the configuration to a new environment it doesn't get the config for this module since it's still being stored in variables. This is a hassle.

When I grep I find these:

```
./plugins/views_data_export_plugin_display_export.inc:734:    $dir = variable_get('views_data_export_directory', 'temporary://views_plugin_display');
./views_data_export.install:177:      $path = variable_get('views_data_export_directory', 'temporary://views_plugin_display');
./views_data_export.module:129:      $expires = variable_get('views_data_export_gc_expires', 604800); // one week
./views_data_export.module:132:      $chunk = variable_get('views_data_export_gc_chunk', 30);
```

---
PR https://github.com/backdrop-contrib/views_data_export/pull/5

**Comment by herbdool** [comment]
@laryn would you be able to test/review?

**Comment by laryn** [comment]
I looked at code and it looks good -- one question came to mind, though. Is there nowhere to adjust these variables/config?

**Comment by herbdool** [comment]
@laryn nope. We can probably leave it that way for now. Someone could either update and import the updated config file or a new feature could be to provide a UI. The config probably doesn't get changed often.

**Comment by herbdool** [comment]
As part of the Bug Fix Squad I've fixed this bug.
